# Generated by Django 2.2.16 on 2020-10-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina_contador',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background'),
        ),
        migrations.AddField(
            model_name='pagina_contador',
            name='foto_background_url',
            field=models.URLField(blank=True, default='https://imgur.com/WvzW9gn.jpg', null=True),
        ),
        migrations.AddField(
            model_name='pagina_footer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background'),
        ),
        migrations.AddField(
            model_name='pagina_footer',
            name='foto_background_url',
            field=models.URLField(blank=True, default='https://imgur.com/nMHYQd9.jpg', null=True),
        ),
        migrations.AddField(
            model_name='pagina_listapresentes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background'),
        ),
        migrations.AddField(
            model_name='pagina_listapresentes',
            name='foto_background_url',
            field=models.URLField(blank=True, default='https://imgur.com/UWpXoS1.jpg', null=True),
        ),
    ]
