# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('preco', models.CharField(blank=True, max_length=300, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
