# Generated by Django 2.2.16 on 2020-10-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201015_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina_frase',
            name='frase',
            field=models.TextField(blank=True, default='Será uma honra ter você no momento mais incrível das nossas vidas, onde finalmente nos tornaremos um.', null=True),
        ),
        migrations.AlterField(
            model_name='pagina_galeria',
            name='texto',
            field=models.TextField(blank=True, default='Nada melhor do que fotos pra registrar tudo!', null=True),
        ),
        migrations.AlterField(
            model_name='pagina_listapresentes',
            name='texto',
            field=models.TextField(blank=True, default='Abaixo, estão as listas que fizemos online. Qualquer dúvida, só entrar em contato com a gente!', null=True),
        ),
        migrations.AlterField(
            model_name='pagina_mural',
            name='texto',
            field=models.TextField(blank=True, default='Por favor, não saia deste site sem deixar um recado para nós. Sua mensagem é muito importante, e gostaríamos de recebê-la. Nós receberemos e publicaremos as melhores em nossa página.', null=True),
        ),
    ]
