# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
